name: Translate README

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      # ISO Langusge Codes: https://cloud.google.com/translate/docs/languages  
      - name: Adding README - Chinese Simplified
        uses: dephraiim/translate-readme@main
        with:
          LANG: zh-CN
      - name: Adding README - Chinese Traditional
        uses: dephraiim/translate-readme@main
        with:
          LANG: zh-TW
      - name: Adding README - Hindi
        uses: dephraiim/translate-readme@main
        with:
          LANG: hi
      - name: Adding README - Arabic
        uses: dephraiim/translate-readme@main
        with:
          LANG: ar
      - name: Adding README - French
        uses: dephraiim/translate-readme@main
        with:
          LANG: fr
          name: Translate README
      - name: Adding README - German
        uses: dephraiim/translate-readme@main
        with:
          LANG: de
      - name: Adding README - Greek
        uses: dephraiim/translate-readme@main
        with:
          LANG: el
      - name: Adding README - Hungarian
        uses: dephraiim/translate-readme@main
        with:
          LANG: hu
      - name: Adding README - Italian
        uses: dephraiim/translate-readme@main
        with:
          LANG: it
      - name: Adding README - Japanese
        uses: dephraiim/translate-readme@main
        with:
          LANG: ja
                - name: Adding README - Korean
        uses: dephraiim/translate-readme@main
        with:
          LANG: ko
      - name: Adding README - Lithuanian
        uses: dephraiim/translate-readme@main
        with:
          LANG: lt
      - name: Adding README - Nepali
        uses: dephraiim/translate-readme@main
        with:
          LANG: ne
      - name: Adding README - Polish
        uses: dephraiim/translate-readme@main
        with:
          LANG: pl
